apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: u2aajken5-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:e5ed08dc35084fa3e9b0aa150d938bee14c6ddbc@sha256:6b6f125c650d0c0c4477936a1de1629434b1fdded36909e53d5209ddbb4705e1
          name: container-image
